mgmt_network_name      = "Pool-wide network associated with eth0"
lan_network_name       = "Pool-wide network associated with eth2"
wan_network_name       = "Pool-wide network associated with eth3"
pool_name              = "protectli"
sr_name                = "Local storage"
firewall_vm_name       = "pfSense-01"
firewall_template_name = "pfSense 2.6 (Hub)"
